# Mòdul 3 - Exercicis de comprovació
Sergi Grau

## Parte 1
Descripció:

En aquesta tasca treballaràs amb la llibreria numpy i amb les dades de la llibreria sklearn.datasets. D'aquesta llibreria descarrega el conjunt de dades denominat Iris. 

Tingues en compte que Iris està conformada per diversos conjunts de dades, dins d'ells, el array denominat: “data” i “target”. També està composta per llistes, per exemple: “feature_*names” i “target_*names”. 

Per a obtenir informació del dataset pots consultar el següent enllaç:

    sklearn.datasets.load_iris

- Exercici 1 

Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.



In [7]:
# pip install scikit-learn

In [8]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [9]:
from sklearn.datasets import load_iris

In [10]:
iris = load_iris()
data = iris.data
target = iris.target

In [11]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [12]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
target.reshape(-1, 1)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [15]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [16]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [18]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [19]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [20]:
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

- Exercici 2

Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.


In [21]:
data.shape

(150, 4)

In [22]:
target.shape

(150,)

In [24]:
import numpy as np
np.shape(target.reshape(-1, 1))

(150, 1)

In [25]:
matriz_iris = np.concatenate((data, target.reshape(-1, 1)), axis = 1)
matriz_iris

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [26]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
matriz_iris[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])


- Exercici 3

Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.


In [28]:
# long petal = 2, long sepal = 0
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [29]:
matriz_iris[:, 2]

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [30]:
np.mean(matriz_iris[:, 2])

3.7580000000000005

In [31]:
round(np.mean(matriz_iris[:, 2]), 2)

3.76

In [32]:
round(np.std(matriz_iris[:, 2]), 2)

1.76

In [33]:
iris.feature_names[0]

'sepal length (cm)'

In [34]:
for i in [0, 2]:
    print(f'media de {iris.feature_names[i]} es {round(np.mean(matriz_iris[:, i]), 2)}')
    print(f'std de {iris.feature_names[i]} es {round(np.std(matriz_iris[:, i]), 2)}')

media de sepal length (cm) es 5.84
std de sepal length (cm) es 0.83
media de petal length (cm) es 3.76
std de petal length (cm) es 1.76


In [35]:
len(matriz_iris)

150

max(arg)


- Exercici 4

Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior. La utilitzaràs d'aquí endavant.


In [36]:
np.random.choice(len(matriz_iris), size = 20, replace = False)

array([ 66,  73,  28,  67, 120,  95,  97, 104, 123,  57,  36, 115,   3,
        20, 129,  62,  78,  58,  76, 112])

In [37]:
muestra_iris = matriz_iris[np.random.choice(len(matriz_iris), size = 20, replace = False), :]
muestra_iris

array([[5.9, 3. , 4.2, 1.5, 1. ],
       [5.1, 3.8, 1.6, 0.2, 0. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [4.5, 2.3, 1.3, 0.3, 0. ],
       [6.3, 2.5, 5. , 1.9, 2. ],
       [5.7, 2.8, 4.1, 1.3, 1. ],
       [7.9, 3.8, 6.4, 2. , 2. ],
       [6.3, 2.7, 4.9, 1.8, 2. ],
       [6.4, 3.2, 5.3, 2.3, 2. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [5.8, 2.6, 4. , 1.2, 1. ],
       [5. , 3.5, 1.3, 0.3, 0. ],
       [5. , 3.3, 1.4, 0.2, 0. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [6.2, 2.8, 4.8, 1.8, 2. ],
       [6.4, 2.7, 5.3, 1.9, 2. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ]])


- Exercici 5

Crea una matriu que mostri:  

    La mitjana de cada característica per espècie. (mean)
    La desviació estàndard de cada característica per espècie. (std)


In [38]:
len(muestra_iris)

20

In [39]:
# especies
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [40]:
# caracteristicas
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [41]:
ultima = muestra_iris[:, -1]
ultima

array([1., 0., 1., 0., 2., 1., 2., 2., 2., 1., 0., 1., 0., 0., 1., 2., 2.,
       0., 1., 1.])

In [42]:
ultima == 1

array([ True, False,  True, False, False,  True, False, False, False,
        True, False,  True, False, False,  True, False, False, False,
        True,  True])

In [43]:
muestra_iris[ultima == 1, :-1]

array([[5.9, 3. , 4.2, 1.5],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [5.8, 2.7, 4.1, 1. ],
       [5.8, 2.6, 4. , 1.2],
       [6.6, 2.9, 4.6, 1.3],
       [5.6, 2.5, 3.9, 1.1],
       [5.5, 2.3, 4. , 1.3]])


- Exercici 6

    Calcula la quantitat de mostres per espècie.
    Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"


In [44]:
np.mean(muestra_iris[ultima == 1, :-1])

3.5

In [45]:
for especie in range(3):
    subconsulta = muestra_iris[ultima == especie, :-1]
    print(f'{iris.target_names[especie]} media es {np.mean(subconsulta, axis=0)}')
    print(f'{iris.target_names[especie]} std es {np.std(subconsulta, axis=0)}')

setosa media es [4.93333333 3.28333333 1.41666667 0.25      ]
setosa std es [0.20548047 0.52094999 0.10671874 0.05      ]
versicolor media es [5.8875 2.7125 4.15   1.25  ]
versicolor std es [0.33330729 0.2204399  0.20615528 0.14142136]
virginica media es [6.58333333 2.95       5.28333333 1.95      ]
virginica std es [0.59278064 0.43493295 0.53359369 0.17078251]


In [46]:
muestra_iris[:, -1]

array([1., 0., 1., 0., 2., 1., 2., 2., 2., 1., 0., 1., 0., 0., 1., 2., 2.,
       0., 1., 1.])

In [47]:
np.bincount(muestra_iris[:, -1].astype(int))

array([6, 8, 6])

In [48]:
medias = []
for especie in range(3):
    subconsulta = muestra_iris[ultima == especie, :-1]
    print(f'{iris.target_names[especie]} media es {np.mean(subconsulta, axis=0)}')
    print(f'{iris.target_names[especie]} std es {np.std(subconsulta, axis=0)}')
    medias.append(np.mean(subconsulta, axis=0))
    

setosa media es [4.93333333 3.28333333 1.41666667 0.25      ]
setosa std es [0.20548047 0.52094999 0.10671874 0.05      ]
versicolor media es [5.8875 2.7125 4.15   1.25  ]
versicolor std es [0.33330729 0.2204399  0.20615528 0.14142136]
virginica media es [6.58333333 2.95       5.28333333 1.95      ]
virginica std es [0.59278064 0.43493295 0.53359369 0.17078251]


In [49]:
medias

[array([4.93333333, 3.28333333, 1.41666667, 0.25      ]),
 array([5.8875, 2.7125, 4.15  , 1.25  ]),
 array([6.58333333, 2.95      , 5.28333333, 1.95      ])]

In [50]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [51]:
medias[:][0]

array([4.93333333, 3.28333333, 1.41666667, 0.25      ])

In [52]:
medias

[array([4.93333333, 3.28333333, 1.41666667, 0.25      ]),
 array([5.8875, 2.7125, 4.15  , 1.25  ]),
 array([6.58333333, 2.95      , 5.28333333, 1.95      ])]

In [53]:
medias[0][0]

4.933333333333334

In [54]:
medias[1][0]

5.8875

In [55]:
medias[2][0]

6.583333333333333

In [56]:
medias[0][:]

array([4.93333333, 3.28333333, 1.41666667, 0.25      ])

In [57]:
[fila[0] for fila in medias]

[4.933333333333334, 5.8875, 6.583333333333333]

In [58]:
max([fila[0] for fila in medias])

6.583333333333333


- Exercici 7

    Calcula la matriu de correlació entre les variables.
    Filtra els valors majors a la mitjana (de l'exercici 3) de la longitud dels pètals i mostra-ho. 
    Troba la mostra amb els pètals més llargs.



In [59]:
np.corrcoef(muestra_iris, rowvar=False)

array([[ 1.        ,  0.07264707,  0.92074334,  0.85000103,  0.84281726],
       [ 0.07264707,  1.        , -0.25224194, -0.26847119, -0.27941574],
       [ 0.92074334, -0.25224194,  1.        ,  0.96273288,  0.94673849],
       [ 0.85000103, -0.26847119,  0.96273288,  1.        ,  0.97458951],
       [ 0.84281726, -0.27941574,  0.94673849,  0.97458951,  1.        ]])

In [60]:
np.mean(matriz_iris[:, 2])

3.7580000000000005

In [61]:
muestra_iris[:, 2] > np.mean(matriz_iris[:, 2])

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True, False,
        True,  True])

In [62]:
muestra_iris[muestra_iris[:, 2] > np.mean(matriz_iris[:, 2])]

array([[5.9, 3. , 4.2, 1.5, 1. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [6.3, 2.5, 5. , 1.9, 2. ],
       [5.7, 2.8, 4.1, 1.3, 1. ],
       [7.9, 3.8, 6.4, 2. , 2. ],
       [6.3, 2.7, 4.9, 1.8, 2. ],
       [6.4, 3.2, 5.3, 2.3, 2. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [5.8, 2.6, 4. , 1.2, 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [6.2, 2.8, 4.8, 1.8, 2. ],
       [6.4, 2.7, 5.3, 1.9, 2. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ]])

In [63]:
max(muestra_iris[:, 2])

6.4

In [64]:
np.argmax(muestra_iris[:, 2])

6

In [65]:
muestra_iris[np.argmax(muestra_iris[:, 2])]

array([7.9, 3.8, 6.4, 2. , 2. ])



## Parte 2
Descripció:

Exercicis amb Dataframes.
- Exercici 1

Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un Pandas Dataframe. Explora les dades que conté, explica breument quines variables hi ha i queda’t únicament amb les columnes que consideris rellevants. Justifica la teva elecció.

Neteja el data set.

    Airlines Delay: Airline on-time statistics and delay causes

Important

Redueix la dimensió del dataset de manera aleatòria per tal d'obtenir un dataset de només 200.000 registres. Tots els exercicis s'han de fer amb aquest dataset reduït.


In [70]:
pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 67.0 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 27.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 17.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [72]:
import pandas as pd
df_inicial= pd.read_csv('DelayedFlights.csv') 
df = df_inicial.sample(n=200_000)
  


- Exercici 2

Fes un informe complet del dataset:

    Resumeix estadísticament el dataset i les columnes d’interès. Fes una anàlisi estadístic del que consideris rellevant.
    Mostra quina és les aerolínies amb més endarreriments acumulats.
    Quins són els vols més llargs?


In [73]:
df.describe()

Unnamed: 0      Year          Month     DayofMonth      DayOfWeek  \
count  2.000000e+05  200000.0  200000.000000  200000.000000  200000.000000   
mean   3.345705e+06    2008.0       6.118100      15.771495       3.986720   
std    2.065707e+06       0.0       3.481517       8.780083       1.994313   
min    1.600000e+01    2008.0       1.000000       1.000000       1.000000   
25%    1.520364e+06    2008.0       3.000000       8.000000       2.000000   
50%    3.247348e+06    2008.0       6.000000      16.000000       4.000000   
75%    4.985170e+06    2008.0       9.000000      23.000000       6.000000   
max    7.009710e+06    2008.0      12.000000      31.000000       7.000000   

            DepTime     CRSDepTime        ArrTime     CRSArrTime  \
count  200000.00000  200000.000000  199283.000000  200000.000000   
mean     1518.71099    1467.662535    1611.177898    1634.011925   
std       450.35387     424.600656     547.037179     464.647480   
min         1.00000       1.000000       1.000000       0.000000   
25%      1203.00000    1135.000000    1316.000000    1325.000000   
50%      1545.00000    1510.000000    1716.000000    1705.000000   
75%      1900.00000    1815.000000    2031.000000    2014.000000   
max      2400.00000    2359.000000    2400.000000    2400.000000   

           FlightNum  ...       Distance         TaxiIn        TaxiOut  \
count  200000.000000  ...  200000.000000  199283.000000  199956.000000   
mean     2191.013155  ...     765.691975       6.800846      18.232036   
std      1947.016688  ...     574.748536       5.184543      14.393707   
min         1.000000  ...      31.000000       0.000000       0.000000   
25%       613.000000  ...     338.000000       4.000000      10.000000   
50%      1546.000000  ...     606.000000       6.000000      14.000000   
75%      3450.000000  ...     998.000000       8.000000      21.000000   
max      9741.000000  ...    4962.000000     160.000000     386.000000   

           Cancelled       Diverted   CarrierDelay   WeatherDelay  \
count  200000.000000  200000.000000  128837.000000  128837.000000   
mean        0.000320       0.003945      19.062125       3.675233   
std         0.017886       0.062685      42.768226      20.741763   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       2.000000       0.000000   
75%         0.000000       0.000000      21.000000       0.000000   
max         1.000000       1.000000    1194.000000    1027.000000   

            NASDelay  SecurityDelay  LateAircraftDelay  
count  128837.000000  128837.000000      128837.000000  
mean       15.182859       0.089671          25.388157  
std        34.197929       1.957251          42.371912  
min         0.000000       0.000000           0.000000  
25%         0.000000       0.000000           0.000000  
50%         2.000000       0.000000           8.000000  
75%        14.000000       0.000000          33.000000  
max       838.000000     193.000000        1316.000000  

[8 rows x 25 columns]

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200000 entries, 1903870 to 1716739
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   Unnamed: 0         200000 non-null  int64  
 1   Year               200000 non-null  int64  
 2   Month              200000 non-null  int64  
 3   DayofMonth         200000 non-null  int64  
 4   DayOfWeek          200000 non-null  int64  
 5   DepTime            200000 non-null  float64
 6   CRSDepTime         200000 non-null  int64  
 7   ArrTime            199283 non-null  float64
 8   CRSArrTime         200000 non-null  int64  
 9   UniqueCarrier      200000 non-null  object 
 10  FlightNum          200000 non-null  int64  
 11  TailNum            200000 non-null  object 
 12  ActualElapsedTime  199147 non-null  float64
 13  CRSElapsedTime     199984 non-null  float64
 14  AirTime            199147 non-null  float64
 15  ArrDelay           199147 non-null  float64
 16  

In [80]:
df_retards=df.groupby('UniqueCarrier')['NASDelay'].sum().sort_values(ascending=False)
df_retards

UniqueCarrier
AA    214125.0
XE    169132.0
OO    166410.0
CO    159684.0
UA    151849.0
MQ    147175.0
WN    134623.0
DL    124189.0
B6    103124.0
US     96097.0
EV     91137.0
FL     79199.0
OH     78192.0
NW     74848.0
YV     72685.0
9E     41234.0
F9     27968.0
AS     24317.0
AQ        79.0
HA        47.0
Name: NASDelay, dtype: float64

In [81]:
df_retards.head(1)

UniqueCarrier
AA    214125.0
Name: NASDelay, dtype: float64

In [89]:
df_llargs = df[['FlightNum','Distance']].groupby('FlightNum').max().sort_values(by='Distance',ascending=False)
df_llargs

Distance
FlightNum          
15             4962
14             4962
851            4502
1282           4502
1273           4502
...             ...
6172             67
6322             67
4086             67
6062             67
6896             64

[7300 rows x 1 columns]


- Exercici 3

Exporta el dataset net i amb les noves columnes a Excel.

In [91]:
pip install openpyxl

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 5.9 MB/s eta 0:00:0000:01
Note: you may need to restart the kernel to use updated packages.


In [92]:
df_llargs.to_excel('exercici_03.xlsx', index=False)
