# Mòdul 3 - Exercicis de comprovació
Sergi Grau

## Parte 1
Descripció:

En aquesta tasca treballaràs amb la llibreria numpy i amb les dades de la llibreria sklearn.datasets. D'aquesta llibreria descarrega el conjunt de dades denominat Iris. 

Tingues en compte que Iris està conformada per diversos conjunts de dades, dins d'ells, el array denominat: “data” i “target”. També està composta per llistes, per exemple: “feature_*names” i “target_*names”. 

Per a obtenir informació del dataset pots consultar el següent enllaç:

    sklearn.datasets.load_iris

- Exercici 1 

Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.



In [1]:
# pip install scikit-learn

In [2]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()
data = iris.data
target = iris.target

In [5]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
target.reshape(-1, 1)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [14]:
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

- Exercici 2

Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.


In [15]:
data.shape

(150, 4)

In [16]:
target.shape

(150,)

In [17]:
import numpy as np
np.shape(target.reshape(-1, 1))

(150, 1)

In [18]:
matriz_iris = np.concatenate((data, target.reshape(-1, 1)), axis = 1)
matriz_iris

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [19]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
matriz_iris[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])


- Exercici 3

Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.


In [21]:
# long petal = 2, long sepal = 0
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [22]:
matriz_iris[:, 2]

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [23]:
np.mean(matriz_iris[:, 2])

3.7580000000000005

In [24]:
round(np.mean(matriz_iris[:, 2]), 2)

3.76

In [25]:
round(np.std(matriz_iris[:, 2]), 2)

1.76

In [26]:
iris.feature_names[0]

'sepal length (cm)'

In [27]:
for i in [0, 2]:
    print(f'media de {iris.feature_names[i]} es {round(np.mean(matriz_iris[:, i]), 2)}')
    print(f'std de {iris.feature_names[i]} es {round(np.std(matriz_iris[:, i]), 2)}')

media de sepal length (cm) es 5.84
std de sepal length (cm) es 0.83
media de petal length (cm) es 3.76
std de petal length (cm) es 1.76


In [28]:
len(matriz_iris)

150

max(arg)


- Exercici 4

Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior. La utilitzaràs d'aquí endavant.


In [29]:
np.random.choice(len(matriz_iris), size = 20, replace = False)

array([ 91, 121,  65, 138,  96,  43,  34,  70, 134, 131, 141,  69,  45,
        13, 107, 118, 106,  52,  87,  61])

In [30]:
muestra_iris = matriz_iris[np.random.choice(len(matriz_iris), size = 20, replace = False), :]
muestra_iris

array([[7.7, 2.8, 6.7, 2. , 2. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [7.7, 3.8, 6.7, 2.2, 2. ],
       [6.7, 3.1, 5.6, 2.4, 2. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [5. , 3.5, 1.6, 0.6, 0. ],
       [6.5, 3. , 5.8, 2.2, 2. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [6.7, 3. , 5.2, 2.3, 2. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [6.3, 2.9, 5.6, 1.8, 2. ],
       [5.8, 2.8, 5.1, 2.4, 2. ],
       [6.1, 3. , 4.9, 1.8, 2. ],
       [7.9, 3.8, 6.4, 2. , 2. ],
       [6.2, 2.8, 4.8, 1.8, 2. ],
       [6.3, 3.3, 6. , 2.5, 2. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [5.1, 3.8, 1.6, 0.2, 0. ]])


- Exercici 5

Crea una matriu que mostri:  

    La mitjana de cada característica per espècie. (mean)
    La desviació estàndard de cada característica per espècie. (std)


In [31]:
len(muestra_iris)

20

In [32]:
# especies
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [33]:
# caracteristicas
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [34]:
ultima = muestra_iris[:, -1]
ultima

array([2., 1., 2., 2., 1., 0., 2., 0., 1., 0., 2., 0., 2., 2., 2., 2., 2.,
       2., 0., 0.])

In [35]:
ultima == 1

array([False,  True, False, False,  True, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [36]:
muestra_iris[ultima == 1, :-1]

array([[6. , 2.2, 4. , 1. ],
       [6.9, 3.1, 4.9, 1.5],
       [6.4, 3.2, 4.5, 1.5]])


- Exercici 6

    Calcula la quantitat de mostres per espècie.
    Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"


In [37]:
np.mean(muestra_iris[ultima == 1, :-1])

3.766666666666667

In [38]:
for especie in range(3):
    subconsulta = muestra_iris[ultima == especie, :-1]
    print(f'{iris.target_names[especie]} media es {np.mean(subconsulta, axis=0)}')
    print(f'{iris.target_names[especie]} std es {np.std(subconsulta, axis=0)}')

setosa media es [5.06666667 3.7        1.51666667 0.28333333]
setosa std es [0.33993463 0.4472136  0.10671874 0.16749793]
versicolor media es [6.43333333 2.83333333 4.46666667 1.33333333]
versicolor std es [0.3681787  0.44969125 0.3681787  0.23570226]
virginica media es [6.71818182 3.11818182 5.70909091 2.12727273]
virginica std es [0.68863261 0.35114923 0.6515081  0.2489648 ]


In [39]:
muestra_iris[:, -1]

array([2., 1., 2., 2., 1., 0., 2., 0., 1., 0., 2., 0., 2., 2., 2., 2., 2.,
       2., 0., 0.])

In [40]:
np.bincount(muestra_iris[:, -1].astype(int))

array([ 6,  3, 11])

In [41]:
medias = []
for especie in range(3):
    subconsulta = muestra_iris[ultima == especie, :-1]
    print(f'{iris.target_names[especie]} media es {np.mean(subconsulta, axis=0)}')
    print(f'{iris.target_names[especie]} std es {np.std(subconsulta, axis=0)}')
    medias.append(np.mean(subconsulta, axis=0))
    

setosa media es [5.06666667 3.7        1.51666667 0.28333333]
setosa std es [0.33993463 0.4472136  0.10671874 0.16749793]
versicolor media es [6.43333333 2.83333333 4.46666667 1.33333333]
versicolor std es [0.3681787  0.44969125 0.3681787  0.23570226]
virginica media es [6.71818182 3.11818182 5.70909091 2.12727273]
virginica std es [0.68863261 0.35114923 0.6515081  0.2489648 ]


In [42]:
medias

[array([5.06666667, 3.7       , 1.51666667, 0.28333333]),
 array([6.43333333, 2.83333333, 4.46666667, 1.33333333]),
 array([6.71818182, 3.11818182, 5.70909091, 2.12727273])]

In [43]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [44]:
medias[:][0]

array([5.06666667, 3.7       , 1.51666667, 0.28333333])

In [45]:
medias

[array([5.06666667, 3.7       , 1.51666667, 0.28333333]),
 array([6.43333333, 2.83333333, 4.46666667, 1.33333333]),
 array([6.71818182, 3.11818182, 5.70909091, 2.12727273])]

In [46]:
medias[0][0]

5.066666666666666

In [47]:
medias[1][0]

6.433333333333334

In [48]:
medias[2][0]

6.718181818181818

In [49]:
medias[0][:]

array([5.06666667, 3.7       , 1.51666667, 0.28333333])

In [50]:
[fila[0] for fila in medias]

[5.066666666666666, 6.433333333333334, 6.718181818181818]

In [51]:
max([fila[0] for fila in medias])

6.718181818181818


- Exercici 7

    Calcula la matriu de correlació entre les variables.
    Filtra els valors majors a la mitjana (de l'exercici 3) de la longitud dels pètals i mostra-ho. 
    Troba la mostra amb els pètals més llargs.



In [52]:
np.corrcoef(muestra_iris, rowvar=False)

array([[ 1.        , -0.11779579,  0.89334339,  0.76058278,  0.76705452],
       [-0.11779579,  1.        , -0.40138725, -0.40892109, -0.46349913],
       [ 0.89334339, -0.40138725,  1.        ,  0.94095796,  0.95137231],
       [ 0.76058278, -0.40892109,  0.94095796,  1.        ,  0.96221288],
       [ 0.76705452, -0.46349913,  0.95137231,  0.96221288,  1.        ]])

In [53]:
np.mean(matriz_iris[:, 2])

3.7580000000000005

In [54]:
muestra_iris[:, 2] > np.mean(matriz_iris[:, 2])

array([ True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
       False, False])

In [55]:
muestra_iris[muestra_iris[:, 2] > np.mean(matriz_iris[:, 2])]

array([[7.7, 2.8, 6.7, 2. , 2. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [7.7, 3.8, 6.7, 2.2, 2. ],
       [6.7, 3.1, 5.6, 2.4, 2. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [6.5, 3. , 5.8, 2.2, 2. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.7, 3. , 5.2, 2.3, 2. ],
       [6.3, 2.9, 5.6, 1.8, 2. ],
       [5.8, 2.8, 5.1, 2.4, 2. ],
       [6.1, 3. , 4.9, 1.8, 2. ],
       [7.9, 3.8, 6.4, 2. , 2. ],
       [6.2, 2.8, 4.8, 1.8, 2. ],
       [6.3, 3.3, 6. , 2.5, 2. ]])

In [56]:
max(muestra_iris[:, 2])

6.7

In [57]:
np.argmax(muestra_iris[:, 2])

0

In [58]:
muestra_iris[np.argmax(muestra_iris[:, 2])]

array([7.7, 2.8, 6.7, 2. , 2. ])



## Parte 2
Descripció:

Exercicis amb Dataframes.
- Exercici 1

Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un Pandas Dataframe. Explora les dades que conté, explica breument quines variables hi ha i queda’t únicament amb les columnes que consideris rellevants. Justifica la teva elecció.

Neteja el data set.

    Airlines Delay: Airline on-time statistics and delay causes

Important

Redueix la dimensió del dataset de manera aleatòria per tal d'obtenir un dataset de només 200.000 registres. Tots els exercicis s'han de fer amb aquest dataset reduït.


In [59]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [60]:
import pandas as pd
df_inicial= pd.read_csv('DelayedFlights.csv') 
df = df_inicial.sample(n=200_000)
  

In [65]:
#una mica de neteja de dades
df = df[~((df.Cancelled == 1) | (df.Diverted == 1))]
df = df.nunique()
df

Unnamed: 0           200000
Year                      1
Month                    12
DayofMonth               31
DayOfWeek                 7
DepTime                1346
CRSDepTime             1146
ArrTime                1437
CRSArrTime             1317
UniqueCarrier            20
FlightNum              7312
TailNum                5277
ActualElapsedTime       571
CRSElapsedTime          475
AirTime                 560
ArrDelay                662
DepDelay                602
Origin                  297
Dest                    298
Distance               1368
TaxiIn                  120
TaxiOut                 239
Cancelled                 2
CancellationCode          4
Diverted                  2
CarrierDelay            524
WeatherDelay            373
NASDelay                390
SecurityDelay            78
LateAircraftDelay       402
dtype: int64


- Exercici 2

Fes un informe complet del dataset:

    Resumeix estadísticament el dataset i les columnes d’interès. Fes una anàlisi estadístic del que consideris rellevant.
    Mostra quina és les aerolínies amb més endarreriments acumulats.
    Quins són els vols més llargs?


In [61]:
df.describe()

Unnamed: 0      Year          Month     DayofMonth      DayOfWeek  \
count  2.000000e+05  200000.0  200000.000000  200000.000000  200000.000000   
mean   3.340495e+06    2008.0       6.108760      15.757830       3.987195   
std    2.068667e+06       0.0       3.487489       8.781429       1.998337   
min    2.100000e+01    2008.0       1.000000       1.000000       1.000000   
25%    1.513144e+06    2008.0       3.000000       8.000000       2.000000   
50%    3.239811e+06    2008.0       6.000000      16.000000       4.000000   
75%    4.972536e+06    2008.0       9.000000      23.000000       6.000000   
max    7.009726e+06    2008.0      12.000000      31.000000       7.000000   

             DepTime     CRSDepTime        ArrTime     CRSArrTime  \
count  200000.000000  200000.000000  199276.000000  200000.000000   
mean     1518.783745    1468.049885    1610.745674    1634.242910   
std       450.753126     424.851092     547.875426     464.908683   
min         1.000000       1.000000       1.000000       1.000000   
25%      1203.000000    1135.000000    1315.000000    1325.000000   
50%      1546.000000    1510.000000    1716.000000    1706.000000   
75%      1901.000000    1815.000000    2031.000000    2015.000000   
max      2400.000000    2359.000000    2400.000000    2400.000000   

           FlightNum  ...       Distance         TaxiIn        TaxiOut  \
count  200000.000000  ...  200000.000000  199276.000000  199939.000000   
mean     2179.001680  ...     766.141425       6.804537      18.197495   
std      1941.257658  ...     574.317491       5.256259      14.324308   
min         1.000000  ...      11.000000       0.000000       0.000000   
25%       611.000000  ...     340.000000       4.000000      10.000000   
50%      1539.000000  ...     606.000000       6.000000      14.000000   
75%      3415.250000  ...     998.000000       8.000000      21.000000   
max      9741.000000  ...    4962.000000     174.000000     337.000000   

           Cancelled       Diverted   CarrierDelay   WeatherDelay  \
count  200000.000000  200000.000000  128676.000000  128676.000000   
mean        0.000385       0.003920      18.949260       3.805030   
std         0.019618       0.062487      42.543246      22.288089   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       2.000000       0.000000   
75%         0.000000       0.000000      21.000000       0.000000   
max         1.000000       1.000000    1542.000000     951.000000   

            NASDelay  SecurityDelay  LateAircraftDelay  
count  128676.000000  128676.000000      128676.000000  
mean       15.044740       0.088237          25.188419  
std        34.070815       1.797112          41.868617  
min         0.000000       0.000000           0.000000  
25%         0.000000       0.000000           0.000000  
50%         2.000000       0.000000           8.000000  
75%        15.000000       0.000000          33.000000  
max      1357.000000     130.000000        1303.000000  

[8 rows x 25 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200000 entries, 68008 to 1331405
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   Unnamed: 0         200000 non-null  int64  
 1   Year               200000 non-null  int64  
 2   Month              200000 non-null  int64  
 3   DayofMonth         200000 non-null  int64  
 4   DayOfWeek          200000 non-null  int64  
 5   DepTime            200000 non-null  float64
 6   CRSDepTime         200000 non-null  int64  
 7   ArrTime            199276 non-null  float64
 8   CRSArrTime         200000 non-null  int64  
 9   UniqueCarrier      200000 non-null  object 
 10  FlightNum          200000 non-null  int64  
 11  TailNum            199999 non-null  object 
 12  ActualElapsedTime  199139 non-null  float64
 13  CRSElapsedTime     199979 non-null  float64
 14  AirTime            199139 non-null  float64
 15  ArrDelay           199139 non-null  float64
 16  De

In [64]:
df.groupby('UniqueCarrier')['ArrDelay'].mean().sort_values(ascending=False)

UniqueCarrier
YV    55.202890
B6    53.877533
OH    51.181094
XE    50.528266
UA    47.848447
EV    47.397572
AA    46.859992
9E    46.544599
OO    45.749239
MQ    45.209124
NW    43.524708
FL    42.246320
DL    39.843802
CO    39.779072
HA    35.320106
US    35.254437
AS    35.243593
WN    30.162863
F9    27.043610
AQ    20.855556
Name: ArrDelay, dtype: float64

In [81]:
df_retards.head(1)

UniqueCarrier
AA    214125.0
Name: NASDelay, dtype: float64

In [89]:
df_llargs = df[['FlightNum','Distance']].groupby('FlightNum').max().sort_values(by='Distance',ascending=False)
df_llargs

Distance
FlightNum          
15             4962
14             4962
851            4502
1282           4502
1273           4502
...             ...
6172             67
6322             67
4086             67
6062             67
6896             64

[7300 rows x 1 columns]


- Exercici 3

Exporta el dataset net i amb les noves columnes a Excel.

In [91]:
pip install openpyxl

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 5.9 MB/s eta 0:00:0000:01
Note: you may need to restart the kernel to use updated packages.


In [92]:
df_llargs.to_excel('exercici_03.xlsx', index=False)
